CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(255) NOT NULL,
    onSale TINYINT(1) DEFAULT 0,
    imageLink VARCHAR(255)
);

INSERT INTO products (name, price, category, onSale, imageLink) VALUES
('Laptop', 999.99, 'Electronics', 0, 'https://example.com/laptop.jpg'),
('Smartphone', 599.99, 'Electronics', 1, 'https://example.com/smartphone.jpg'),
('T-shirt', 19.99, 'Clothing', 1, 'https://example.com/tshirt.jpg'),
('Jeans', 49.99, 'Clothing', 0, 'https://example.com/jeans.jpg'),
('Book', 9.99, 'Books', 0, 'https://example.com/book.jpg'),
('Headphones', 79.99, 'Electronics', 1, 'https://example.com/headphones.jpg'),
('Running Shoes', 89.99, 'Sports', 0, 'https://example.com/runningshoes.jpg'),
('Sneakers', 69.99, 'Sports', 1, 'https://example.com/sneakers.jpg'),
('Coffee Maker', 129.99, 'Home & Kitchen', 1, 'https://example.com/coffeemaker.jpg'),
('Blender', 59.99, 'Home & Kitchen', 0, 'https://example.com/blender.jpg'),
('Toy Car', 24.99, 'Toys', 0, 'https://example.com/toycar.jpg'),
('Doll', 29.99, 'Toys', 1, 'https://example.com/doll.jpg'),
('Desk Lamp', 39.99, 'Home & Kitchen', 1, 'https://example.com/desklamp.jpg'),
('Backpack', 49.99, 'Fashion Accessories', 0, 'https://example.com/backpack.jpg'),
('Watch', 149.99, 'Fashion Accessories', 1, 'https://example.com/watch.jpg'),
('Desk Organizer', 19.99, 'Office Supplies', 0, 'https://example.com/deskorganizer.jpg'),
('Notebook', 4.99, 'Office Supplies', 1, 'https://example.com/notebook.jpg'),
('Gaming Console', 299.99, 'Electronics', 0, 'https://example.com/gamingconsole.jpg'),
('Board Game', 39.99, 'Toys', 1, 'https://example.com/boardgame.jpg'),
('Printer', 199.99, 'Electronics', 0, 'https://example.com/printer.jpg'),
('Vacuum Cleaner', 149.99, 'Home & Kitchen', 1, 'https://example.com/vacuumcleaner.jpg'),
('Pillow', 29.99, 'Home & Kitchen', 0, 'https://example.com/pillow.jpg'),
('Hoodie', 39.99, 'Clothing', 1, 'https://example.com/hoodie.jpg'),
('Sunglasses', 79.99, 'Fashion Accessories', 0, 'https://example.com/sunglasses.jpg'),
('Candle Holder', 14.99, 'Home Decor', 1, 'https://example.com/candleholder.jpg'),
('Plant Pot', 24.99, 'Home Decor', 0, 'https://example.com/plantpot.jpg'),
('Hair Dryer', 49.99, 'Beauty', 1, 'https://example.com/hairdryer.jpg'),
('Makeup Kit', 59.99, 'Beauty', 0, 'https://example.com/makeupkit.jpg'),
('Basketball', 29.99, 'Sports', 1, 'https://example.com/basketball.jpg'),
('Soccer Ball', 19.99, 'Sports', 0, 'https://example.com/soccerball.jpg'),
('Chess Set', 34.99, 'Games', 1, 'https://example.com/chessset.jpg'),
('Laptop Bag', 49.99, 'Electronics Accessories', 0, 'https://example.com/laptopbag.jpg'),
('External Hard Drive', 79.99, 'Electronics Accessories', 1, 'https://example.com/externalharddrive.jpg'),
('Teapot', 24.99, 'Home & Kitchen', 0, 'https://example.com/teapot.jpg'),
('Tea Cup Set', 29.99, 'Home & Kitchen', 1, 'https://example.com/teacupset.jpg'),
('Fitness Tracker', 89.99, 'Sports', 0, 'https://example.com/fitnesstracker.jpg'),
('Yoga Mat', 39.99, 'Sports', 1, 'https://example.com/yogamat.jpg'),
('Bluetooth Speaker', 69.99, 'Electronics', 0, 'https://example.com/bluetoothspeaker.jpg'),
('Wireless Mouse', 19.99, 'Electronics Accessories', 1, 'https://example.com/wirelessmouse.jpg'),
('Earbuds', 49.99, 'Electronics Accessories', 0, 'https://example.com/earbuds.jpg'),
('Desk Chair', 149.99, 'Home & Kitchen', 1, 'https://example.com/deskchair.jpg'),
('Cookware Set', 199.99, 'Home & Kitchen', 0, 'https://example.com/cookwareset.jpg'),
('Jacket', 79.99, 'Clothing', 1, 'https://example.com/jacket.jpg'),
('Scarf', 19.99, 'Clothing', 0, 'https://example.com/scarf.jpg'),
('Wallet', 49.99, 'Fashion Accessories', 1, 'https://example.com/wallet.jpg'),
('Briefcase', 99.99, 'Fashion Accessories', 0, 'https://example.com/briefcase.jpg'),
('Desk Clock', 29.99, 'Home & Kitchen', 1, 'https://example.com/deskclock.jpg'),
('Wall Clock', 39.99, 'Home & Kitchen', 0, 'https://example.com/wallclock.jpg'),
('Throw Pillow', 19.99, 'Home Decor', 1, 'https://example.com/throwpillow.jpg'),
('Picture Frame', 14.99, 'Home Decor', 0, 'https://example.com/pictureframe.jpg'),
('Cookbook', 24.99, 'Books', 1, 'https://example.com/cookbook.jpg'),
('Desk Lamp', 34.99, 'Home & Kitchen', 0, 'https://example.com/desklamp.jpg'),
('Dining Table', 299.99, 'Home & Kitchen', 1, 'https://example.com/diningtable.jpg'),
('Kitchen Knife Set', 79.99, 'Home & Kitchen', 0, 'https://example.com/kitchenknifeset.jpg'),
('Tool Set', 49.99, 'Tools', 1, 'https://example.com/toolset.jpg'),
('Gardening Gloves', 14.99, 'Gardening', 0, 'https://example.com/gardeninggloves.jpg'),
('Paintbrush Set', 19.99, 'Art Supplies', 1, 'https://example.com/paintbrushset.jpg'),
('Watercolor Paints', 29.99, 'Art Supplies', 0, 'https://example.com/watercolorpaints.jpg'),
('Printer Paper', 9.99, 'Office Supplies', 1, 'https://example.com/printerpaper.jpg'),
('Desk Organizer', 24.99, 'Office Supplies', 0, 'https://example.com/deskorganizer2.jpg'),
('USB Flash Drive', 14.99, 'Electronics Accessories', 1, 'https://example.com/usbflashdrive.jpg'),
('Mouse Pad', 9.99, 'Electronics Accessories', 0, 'https://example.com/mousepad.jpg'),
('Bean Bag Chair', 79.99, 'Home & Kitchen', 1, 'https://example.com/beanbagchair.jpg'),
('Travel Backpack', 59.99, 'Travel', 0, 'https://example.com/travelbackpack.jpg'),
('Carry-on Luggage', 129.99, 'Travel', 1, 'https://example.com/carryonluggage.jpg'),
('Sunscreen', 14.99, 'Beauty', 0, 'https://example.com/sunscreen.jpg'),
('Facial Cleanser', 29.99, 'Beauty', 1, 'https://example.com/facialcleanser.jpg'),
('Winter Gloves', 19.99, 'Clothing', 0, 'https://example.com/wintergloves.jpg'),
('Baseball Cap', 14.99, 'Clothing', 1, 'https://example.com/baseballcap.jpg'),
('Tennis Racket', 89.99, 'Sports', 0, 'https://example.com/tennisracket.jpg'),
('Ping Pong Paddle', 24.99, 'Sports', 1, 'https://example.com/pingpong.jpg'),
('Handbag', 59.99, 'Fashion Accessories', 0, 'https://example.com/handbag.jpg'),
('Necklace', 39.99, 'Fashion Accessories', 1, 'https://example.com/necklace.jpg'),
('Fishing Rod', 49.99, 'Sports', 0, 'https://example.com/fishingrod');

UPDATE products SET imageLink = 'https://previews.123rf.com/images/aquir/aquir1311/aquir131100316/23569861-sample-grunge-red-round-stamp.jpg';
